# Generated by Django 5.1.5 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
