# Generated by Django 5.1.5 on 2025-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0002_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
