# Generated by Django 5.1.5 on 2025-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0003_alter_info_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='info',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='info',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='info',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
