# Generated by Django 5.1.5 on 2025-02-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0004_mainservices_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservices',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geodesy.mainservices')),
            ],
        ),
    ]
