# Generated by Django 5.1.5 on 2025-02-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0005_alter_mainservices_options_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservices',
            options={'verbose_name': 'Категория услуги', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='info',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainservices',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geodesy.mainservices', verbose_name='Категория услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Стоимость'),
        ),
    ]
