# Generated by Django 5.1.5 on 2025-02-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0006_alter_mainservices_options_alter_services_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('display_client', models.BooleanField(default=False, verbose_name='Отображение у клиента')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geodesy.mainservices', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
