# Generated by Django 5.1.5 on 2025-02-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0007_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='users/files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='geodesy.orders', verbose_name='Заказ')),
            ],
        ),
    ]
