# Generated by Django 5.1.5 on 2025-03-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0008_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='users/files/'),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='geodesy.orders', verbose_name='Заказ'),
        ),
    ]
