# Generated by Django 5.1.5 on 2025-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodesy', '0009_alter_orderfile_file_alter_orderfile_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время заявки')),
                ('status', models.BooleanField(default=False, verbose_name='Отработан ли звонок?')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-time_create'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
